[build]
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9.4.0"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[[edge_functions]]
  path = "/open"
  function = "open"
