[build]
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "7.24.1"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[[edge_functions]]
  path = "/open"
  function = "open"
